apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bigdata-notebook-service.fullname" . }}
  labels:
    {{- include "bigdata-notebook-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bigdata-notebook-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bigdata-notebook-service.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bigdata-notebook-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: session-storage
        persistentVolumeClaim:
          claimName: {{ .Values.sessionStoragePvcName }}
      # This initContainers section should not be needed if the
      # securityContext.fsGroup entry above wasn't ignored, but unfortunately
      # it is ignored for NFS volumes:
      # https://github.com/kubernetes/examples/issues/260
      initContainers:
      - name: nfs-fixer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: session-storage
          mountPath: "/mnt"
        command:
        - sh
        - -c
        - (chmod 0775 /mnt; chgrp 1000 /mnt)
      containers:
        - name: bigdata-notebook-service
          ports:
          - name: proxy
            containerPort: {{ .Values.port }}
            protocol: TCP
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
          - name: session-storage
            mountPath: "/mnt"
          livenessProbe:
            exec:
              command:
                - bash
                - check-liveness.sh
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: EG_PORT
            value: {{ .Values.port | quote }}
          - name: EG_BASE_URL
            value: {{ .Values.egBaseUrl }}
          - name: EG_NAMESPACE
            value: {{ .Release.Namespace }}
          - name: EG_CULL_IDLE_TIMEOUT
            value: {{ .Values.kernel.cullIdleTimeout | quote }}
          - name: EG_LOG_LEVEL
            value: {{ .Values.egLogLevel }}
          - name: EG_KERNEL_LAUNCH_TIMEOUT
            value: {{ .Values.kernel.launchTimeout | quote }}
          - name: OFAS_KERNEL_NAMESPACE
            value: {{ .Values.kernel.namespace }}
          - name: SPOTINST_BASE_URL
            value: {{ .Values.spotBaseUrl }}
          - name: EG_RESPONSE_IP
            value: "{{ .Values.kernel.connectionServiceName }}.{{ .Release.Namespace }}.svc.cluster.local"
          - name: EG_PORT_RANGE
            value: "{{ .Values.kernel.portMin }}..{{ .Values.kernel.portMax }}"
          - name: EG_MIN_PORT_RANGE_SIZE  # This one needs to match the range above or JEG won't start
            value: "{{ sub .Values.kernel.portMax .Values.kernel.portMin }}"
          - name: EG_KERNEL_SESSION_PERSISTENCE
            value: "True"
          - name: EG_PERSISTENCE_ROOT
            value: "/mnt"
          - name: SPOTINST_CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: spot-ofas-cluster-info
                key: clusterId
          - name: SPOTINST_ACCOUNT_ID
            valueFrom:
              configMapKeyRef:
                name: spot-ofas-cluster-info
                key: accountId
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
