---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigdata-notebook-service.fullname" . }}-kernels
  labels:
    {{- include "bigdata-notebook-service.labels" . | nindent 4 }}      
spec:
  selector:
    {{- include "bigdata-notebook-service.selectorLabels" . | nindent 4 }}
  ports:
  {{- range untilStep (.Values.kernel.portMin | int) (add1 .Values.kernel.portMax | int) 1 }}
  - protocol: TCP
    name: kernel-{{ . }}
    port: {{ . }}
    targetPort: {{ . }}
  {{- end }}
  sessionAffinity: ClientIP
  type: ClusterIP

