apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bigdata-notebook-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - 'configmaps'
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bigdata-notebook-service.fullname" . }}-pod-watcher
rules:
  - apiGroups:
      - ""
    resources:
      - 'pods'
    verbs:
      - get
      - list
      - watch
