---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigdata-notebook-service.fullname" . }}
  labels:
    {{- include "bigdata-notebook-service.labels" . | nindent 4 }}
spec:
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: proxy
  selector:
    {{- include "bigdata-notebook-service.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigdata-notebook-service.name" . }}
  labels:
    {{- include "bigdata-notebook-service.labels" . | nindent 4 }}
spec:
  ports:
    - name: proxy
      port: 80
      protocol: TCP
      targetPort: proxy
  selector:
    {{- include "bigdata-notebook-service.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  type: ClusterIP
