apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigdata-notebook-service.fullname" . }}-telemetry-cm
  labels:
  {{- include "bigdata-notebook-service.labels" . | nindent 4 }}
data:
  custom-filters.conf: |
    [FILTER]
        Name    grep
        Match   kube.*
        Regex   $kubernetes['labels']['bigdata.spot.io/component'] {{ index .Values.podLabels "bigdata.spot.io/component" }}

  metrics-collection.conf: |
    # Configuration for collecting metrics from the notebook service
