apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bigdata-deployer-admin
  namespace: spot-system
  labels:
    bigdata.spot.io/resource: deployer-rbac
  annotations:
    {{- if .Values.useHelmHooks }}
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/resource-policy: keep
    {{- /* Delete the previous resource before a new hook is launched */}}
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "2"
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: bigdata-deployer
    namespace: spot-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bigdata-deployer-cluster-manager
  labels:
    bigdata.spot.io/resource: deployer-rbac
  annotations:
    {{- if .Values.useHelmHooks }}
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/resource-policy: keep
    {{- /* Delete the previous resource before a new hook is launched */}}
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "1"
    {{- end }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]
  - apiGroups: ["bigdata.spot.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["spotinst-kubernetes-cluster-controller-config"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["spotinst-kubernetes-cluster-controller"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["spot-bigdata-tls", "spot-bigdata-image-pull", "spot-bigdata-log-collector-creds", "spot-bigdata-telemetry-creds"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: ["scheduling.k8s.io"]
    resources: ["priorityclasses"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["*"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "watch", "delete", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs: ["create", "get", "watch", "delete", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["get", "list", "watch"]
    {{- if .Values.rbac.allowRoleEscalation }}
    # Used in automatic upgrades
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    resourceNames:
      - "bigdata-deployer-cluster-manager"
    verbs: ["escalate"]
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bigdata-deployer-cluster-manager
  labels:
    bigdata.spot.io/resource: deployer-rbac
  annotations:
    {{- if .Values.useHelmHooks }}
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/resource-policy: keep
    {{- /* Delete the previous resource before a new hook is launched */}}
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "2"
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bigdata-deployer-cluster-manager
subjects:
  - kind: ServiceAccount
    name: bigdata-deployer
    namespace: spot-system
