apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bigdata-deployer-admin
  namespace: spot-system
  labels:
    bigdata.spot.io/resource: deployer-rb
  annotations:
    {{- if .Values.useHelmHooks }}
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/resource-policy: keep
    {{- /* Delete the previous resource before a new hook is launched */}}
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "3"
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: bigdata-deployer
    namespace: spot-system