apiVersion: v1
kind: ServiceAccount
metadata:
  name: bigdata-deployer
  namespace: spot-system
  labels:
    bigdata.spot.io/resource: deployer-sa
  annotations:
    {{- if .Values.useHelmHooks }}
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
    {{- /* Delete the previous resource before a new hook is launched */}}
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "2"
    {{- end }}