spark-operator:
  image:
    registry: public.ecr.aws
    repository: ocean-spark/spark-operator
    tag: 251fdb1

  spark:
    jobNamespaces: [""]
    serviceAccount:
      create: false
    rbac:
      create: false

  controller:
    workers: 20
    uiService:
      enable: false
    pprof:
      enable: true
    labels:
      bigdata.spot.io/component: "spark-operator-controller"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: spotinst.io/ocean-vng-id
                operator: Exists
              - key: bigdata.spot.io/vng
                operator: NotIn
                values:
                - ocean-spark
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: bigdata.spot.io/component
                    operator: Exists
              topologyKey: "kubernetes.io/hostname"
    toleration:
      - key: "bigdata.spot.io/unschedulable"
        operator: "Equal"
        value: "ocean-spark-system"
        effect: "NoSchedule"
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
    volumes:
      - name: telementry-global-config
        configMap:
          name: bigdata-common-telemetry-fluentbit-cm
      - name: telementry-custom-config
        configMap:
          name: spark-operator-static-telemetry-cm
      - name: telemetry-aws-credentials
        secret:
          secretName: spot-bigdata-telemetry-creds
      - name: varlog
        hostPath:
          path: /var/log/
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

  webhook:
    labels:
      bigdata.spot.io/component: "spark-operator-webhook"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: spotinst.io/ocean-vng-id
                operator: Exists
              - key: bigdata.spot.io/vng
                operator: NotIn
                values:
                - ocean-spark
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: bigdata.spot.io/component
                    operator: Exists
              topologyKey: "kubernetes.io/hostname"
    toleration:
      - key: "bigdata.spot.io/unschedulable"
        operator: "Equal"
        value: "ocean-spark-system"
        effect: "NoSchedule"
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
    volumes:
      - name: telementry-global-config
        configMap:
          name: bigdata-common-telemetry-fluentbit-cm
      - name: telementry-custom-config
        configMap:
          name: spark-operator-static-telemetry-cm
      - name: telemetry-aws-credentials
        secret:
          secretName: spot-bigdata-telemetry-creds
      - name: varlog
        hostPath:
          path: /var/log/
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

  telemetry:
    enabled: true