kind: Service
apiVersion: v1
metadata:
  name: {{ include "bigdata-notebook-service-storage-server.fullname" . }}
  labels:
    {{- include "bigdata-notebook-service-storage-server.labels" . | nindent 4 }}
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    {{- include "bigdata-notebook-service-storage-server.selectorLabels" . | nindent 4 }}
