# Default values for bigdata-spark-watcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 066597193667.dkr.ecr.us-east-1.amazonaws.com/private/bigdata-spark-watcher
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.1.3-db2de814

imagePullSecrets:
  - name: spot-bigdata-image-pull

nameOverride: ""
fullnameOverride: ""

envVars:
  - name: SPOTINST_BASE_URL
    value: https://api.spotinst.io

# Spark Application watch label - used to select sparkApplication custom resources
saWatchLabel: ""

serviceAccount:
  create: true
  annotations: {}
  name: bigdata-spark-watcher

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 50Mi

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: spotinst.io/node-lifecycle
          operator: In
          values:
          - od
