# Default values for bigdata-spark-watcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: public.ecr.aws/l8m2k1n1/netapp/bigdata-spark-watcher
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.0.4-b02a9abc

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Spark Application watch label - used to select sparkApplication custom resources
saWatchLabel: ""

serviceAccount:
  create: true
  annotations: {}
  name: bigdata-spark-watcher

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 50Mi

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: spotinst.io/node-lifecycle
          operator: In
          values:
          - od
