{{- $root := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigdata-telemetry.fullname" . }}-prometheus-agent-cm
  labels:
    {{- include "bigdata-telemetry.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
{{ $root.Values.prometheus.config.global | toYaml | trimSuffix "\n" | indent 6 }}
    remote_write:
      - url: http://{{ include "bigdata-telemetry.fullname" . }}-thanos-receiver-svc.{{ include "bigdata-telemetry.fullname" . }}.svc.cluster.local:19291/api/v1/receive
        metadata_config:
          send: false
    scrape_configs:
{{ tpl $root.Values.prometheus.config.scrape_configs $root | indent 6 }}