---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigdata-telemetry.fullname" . }}-thanos-receiver-svc
  labels:
    {{- include "bigdata-telemetry.labels" . | nindent 4 }}
spec:
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  - name: remote-write
    port: 19291
    targetPort: 19291
  selector:
    {{- include "bigdata-telemetry.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigdata-telemetry.name" . }}-thanos-receiver-svc
  labels:
    {{- include "bigdata-telemetry.labels" . | nindent 4 }}
spec:
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  - name: remote-write
    port: 19291
    targetPort: 19291
  selector:
    {{- include "bigdata-telemetry.selectorLabels" . | nindent 4 }}