---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigdata-telemetry.fullname" . }}-thanos-receiver-cm
  labels:
    {{- include "bigdata-telemetry.labels" . | nindent 4 }}
data:
  hashrings.json: |-
    [
      {
        "endpoints": [
          "{{ include "bigdata-telemetry.fullname" . }}-thanos-receiver-svc.{{ .Release.Namespace }}.svc.cluster.local:10901"
        ]
      }
    ]