---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigdata-telemetry.fullname" . }}-thanos-receiver-cm
  labels:
    {{- include "bigdata-telemetry.labels" . | nindent 4 }}
data:
  hashrings.json: |-
    [
      {
        "endpoints": [
          "127.0.0.1:10901"
        ]
      }
    ]