{{- if .Values.telemetry.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-operator.fullname" . }}-custom-fluentbit-cm
  labels:
  {{- include "spark-operator.labels" . | nindent 4 }}
data:
  custom-filters.conf: |
    [FILTER]
        Name    grep
        Match   kube.*
        Regex   $kubernetes['labels']['bigdata.spot.io/component'] {{ include "spark-operator.fullname" . }}
{{- end }}
