{{- /* Added by OfAS */}}
{{- if .Values.pprof.enable -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-operator.fullname" . }}-pprof
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Values.pprof.portName }}
      port: {{ .Values.pprof.port }}
      protocol: TCP
      targetPort: {{ .Values.pprof.portName }}
  selector:
    {{- include "spark-operator.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
{{ end }}