{{- /*
      Added by OfAS.
      Namespaced RBAC for the spot-system namespace.
      We have moved some unnecessary cluster wide privileges to here.
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "spark-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "spark-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spark-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}


