{{- if .Values.telemetry.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-operator.fullname" . }}-telemetry-cm
  labels:
  {{- include "spark-operator.labels" . | nindent 4 }}
data:
  custom-filters.conf: |
    [FILTER]
        Name    grep
        Match   kube.*
        Regex   $kubernetes['labels']['bigdata.spot.io/component'] {{ index .Values.podLabels "bigdata.spot.io/component" | quote }}

  metrics-collection.conf: |
    ## Configuration for collecting metrics from the spark operator
    {{- if .Values.metrics.enable }}
    [INPUT]
      name                    prometheus_scrape
      host                    0.0.0.0
      port                    {{ .Values.metrics.port }}
      tag                     {{ include "spark-operator.fullname" . }}
      metrics_path            {{ .Values.metrics.endpoint }}
      scrape_interval         5s

    [OUTPUT]
      Name                 prometheus_remote_write
      Match                {{ include "spark-operator.fullname" . }}
      Host                 bigdata-telemetry-thanos-receiver-svc.{{ .Release.Namespace }}.svc.cluster.local
      Port                 19291
      uri                  /api/v1/receive
      tls                  off
      tls.verify           off
      Workers              1
    {{- end }}
{{- end }}
