apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "bigdata-notebook-service-storage.fullname" . }}
  labels:
    {{- include "bigdata-notebook-service-storage.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server.address }}
    path: {{ .Values.nfs.server.path | quote }}
