---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ .Values.targetGroupBindingName }}
  labels:
    bigdata.spot.io/resource: ingress-target-group-binding
    {{- include "bigdata-ingress-addons.labels" . | nindent 4 }}
spec:
  serviceRef:
    name: {{ .Values.serviceRef.name }}
    port: {{ .Values.serviceRef.port }}
  targetGroupARN: {{ .Values.targetGroupARN }}
