{{- if .Values.targetGroupBinding.create }}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ .Values.targetGroupBinding.name }}
  labels:
    bigdata.spot.io/resource: ingress-target-group-binding
    {{- include "bigdata-ingress-addons.labels" . | nindent 4 }}
spec:
  serviceRef:
    name: {{ .Values.targetGroupBinding.serviceRef.name }}
    port: {{ .Values.targetGroupBinding.serviceRef.port }}
  targetGroupARN: {{ .Values.targetGroupBinding.targetGroupARN }}
{{- end }}
