nameOverride: ""
fullnameOverride: ""

sparkAppsNamespace:
  create: true
  name: spark-apps

sparkDriverServiceAccount:
  annotations: {}
  name: spark-driver

sparkPodsPreemptionPolicy: Never

createPriorityClasses: true