apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.sparkAppsNamespace.name }}
  name: pod-manager
  labels:
  {{- include "spark-operator-static.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "pods" ]
    verbs: [ "create", "get", "watch", "delete", "list", "patch" ]
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "configmaps" ]
    verbs: [ "create", "get", "watch", "delete", "list", "patch" ]
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "pods/exec" ]
    verbs: [ "get" ]
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "pods/log" ]
    verbs: [ "get" ]
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "services" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "persistentvolumeclaims" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver-pod-manager-rb
  namespace: {{ .Values.sparkAppsNamespace.name }}
  labels:
  {{- include "spark-operator-static.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.sparkDriverServiceAccount.name }}
    namespace: {{ .Values.sparkAppsNamespace.name }}
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
