apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-operator-static-telemetry-cm
  labels:
  {{- include "spark-operator-static.labels" . | nindent 4 }}
data:
  custom-filters.conf: |
    [FILTER]
        Name    grep
        Match   kube.*
        Logical_Op or
        Regex   $kubernetes['labels']['bigdata.spot.io/component'] spark-operator-controller
        Regex   $kubernetes['labels']['bigdata.spot.io/component'] spark-operator-webhook

  metrics-collection.conf: |
    ## Configuration for collecting metrics from the spark operator
    [INPUT]
      name                    prometheus_scrape
      host                    0.0.0.0
      port                    8080
      tag                     spark-operator
      metrics_path            /metrics
      scrape_interval         5s

    [OUTPUT]
      Name                 prometheus_remote_write
      Match                spark-operator
      Host                 bigdata-telemetry-thanos-receiver-svc.{{ .Release.Namespace }}.svc.cluster.local
      Port                 19291
      uri                  /api/v1/receive
      tls                  off
      tls.verify           off
      Workers              1
