# Default values for bigdata-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: public.ecr.aws/f4k1p1n4/bigdata-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.4.7-5cf3b94b

imagePullSecrets: []

spotBaseUrl: "https://api.spotinst.io"

oceanControllerNamespace: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""  # Defaults to release name

rbac:
  ingressNginxEnabled: true

podAnnotations: {}

podLabels:
  bigdata.spot.io/component: "bigdata-operator"

podSecurityContext: {}
# fsGroup: 2000

securityContext:
  runAsNonRoot: true
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

telemetry:
  enabled: false
  fluentbit:
    image:
      repository: public.ecr.aws/ocean-spark/fluent-bit
      tag: 2.0.10
    configMap:
      parsers: |
        [PARSER]
            # http://rubular.com/r/tjUt3Awgg4
            Name cri
            Format regex
            Regex ^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z)\t(?<level>[A-Z]+)\t(?<logger>[^\s]+)\t(?<message>.*)$
            Time_Key    time
            Time_Format %Y-%m-%dT%H:%M:%S.%L%z

      config: |
        [SERVICE]
            Flush        1
            Log_Level    info
            Parsers_File parsers.conf
            HTTP_Server   On
            HTTP_Listen   0.0.0.0
            HTTP_Port     2020

        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            Parser cri
            Tag kube.*
            Mem_Buf_Limit 5MB

        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On

        [FILTER]
            Name modify
            Match kube.*
            Add ClusterId ${CLUSTER_ID}
            Add AccountID ${ACCOUNT_ID}

        [FILTER]
            Name    grep
            Match   kube.*
            Regex   $kubernetes['labels']['bigdata.spot.io/component'] .

        [OUTPUT]
            Name s3
            Match kube.*
            bucket                       ${AWS_BUCKET_NAME}
            region                       ${AWS_REGION}
            use_put_object               On
            total_file_size              5M
            upload_timeout               5m

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi

nodeSelector: {}

tolerations:
- key: "bigdata.spot.io/unschedulable"
  operator: "Equal"
  value: "ocean-spark-system"
  effect: "NoSchedule"
- key: "kubernetes.azure.com/scalesetpriority"
  operator: "Equal"
  value: "spot"
  effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: spotinst.io/ocean-vng-id
          operator: Exists
        - key: bigdata.spot.io/vng
          operator: NotIn
          values:
          - ocean-spark
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      preference:
        matchExpressions:
        - key: spotinst.io/node-lifecycle
          operator: In
          values:
          - od
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: bigdata.spot.io/component
            operator: Exists
        topologyKey: "kubernetes.io/hostname"
