# Default values for bigdata-proxy
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 066597193667.dkr.ecr.us-east-1.amazonaws.com/private/bigdata-proxy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.5.7-fd2891a5

imagePullSecrets:
  - name: spot-bigdata-image-pull

port: 8080
logLimit: 0
eventTimeout: 10m
defaultSparkAppsNamespace: spark-apps
logLevel: info
upstreamTTL: 5m

ingress:
  create: true
  prefixPath: ""  # Defaults to bigdata-proxy.fullname
  ingressClassName: spot-bigdata-nginx
  readTimeout: 600
  host: ""  # Overridden at deploy time
  secretNamespace: ""  # Overridden at deploy time
  secretName: ""  # Overridden at deploy time
  bodySize: "15M"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: bigdata-proxy

podAnnotations: {}

podLabels:
  bigdata.spot.io/component: "bigdata-proxy"

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsNonRoot: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi

telemetry:
  enabled: false
  fluentbit:
    image:
      repository: public.ecr.aws/ocean-spark/fluent-bit
      tag: 3.0.5

nodeSelector: {}

tolerations:
- key: "bigdata.spot.io/unschedulable"
  operator: "Equal"
  value: "ocean-spark-system"
  effect: "NoSchedule"
- key: "kubernetes.azure.com/scalesetpriority"
  operator: "Equal"
  value: "spot"
  effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: spotinst.io/node-lifecycle
          operator: In
          values:
          - od
        - key: spotinst.io/ocean-vng-id
          operator: Exists
        - key: bigdata.spot.io/vng
          operator: NotIn
          values:
          - ocean-spark
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: bigdata.spot.io/component
            operator: Exists
        topologyKey: "kubernetes.io/hostname"
