# Default values for bigdata-proxy
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 066597193667.dkr.ecr.us-east-1.amazonaws.com/private/bigdata-proxy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.0.1-3991fec8

imagePullSecrets:
  - name: spot-bigdata-image-pull

port: 8080
logLimit: 200
eventTimeout: 1m
sparkAppsNamespace: spark-apps

ingress:
  create: true
  prefixPath: /bdproxy/?(.*)
  ingressClassName: spot-bigdata-nginx

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: bigdata-proxy

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 50Mi

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: spotinst.io/node-lifecycle
          operator: In
          values:
          - od
