apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bigdata-proxy.fullname" . }}
rules:
  - apiGroups:
      - bigdata.spot.io
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - bigdata.spot.io
    resources:
      - "bigdatacomponents"
    verbs:
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - create
      - update
      - delete
  - apiGroups:
      - sparkoperator.k8s.io
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
