apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bigdata-proxy.fullname" . }}
  labels:
    {{- include "bigdata-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bigdata-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bigdata-proxy.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bigdata-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: bigdata-proxy
          ports:
          - name: proxy
            containerPort: {{ .Values.port }}
            protocol: TCP
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BIGDATA_PROXY_PORT
              value: "{{ .Values.port }}"
            - name: BIGDATA_PROXY_LOG_LIMIT
              value: "{{ .Values.logLimit }}"
            - name: BIGDATA_PROXY_EVENT_TIMEOUT
              value: "{{ .Values.eventTimeout }}"
            - name: BIGDATA_PROXY_APPS_NAMESPACE
              value: "{{ .Values.defaultSparkAppsNamespace }}"
            - name: BIGDATA_PROXY_LOG_LEVEL
              value: "{{ .Values.logLevel }}"
            - name: BIGDATA_PROXY_UPSTREAM_TTL
              value: "{{ .Values.upstreamTTL }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- if .Values.telemetry.enabled }}
        - name: fluentbit
          image: "{{ .Values.telemetry.fluentbit.image.repository }}:{{ .Values.telemetry.fluentbit.image.tag }}"
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          env:
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: spot-bigdata-telemetry-creds
                  key: AWS_BUCKET_NAME
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: spot-bigdata-telemetry-creds
                  key: AWS_REGION
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: spot-ofas-cluster-info
                  key: clusterId
            - name: ACCOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: spot-ofas-cluster-info
                  key: accountId
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: custom-filters
              mountPath: /fluent-bit/etc/custom-filters.conf
              subPath: custom-filters.conf
            - name: varlog
              readOnly: true
              mountPath: /var/log/
            - name: varlibdockercontainers
              readOnly: true
              mountPath: /var/lib/docker/containers
            - name: telemetry-aws-credentials
              mountPath: /root/.aws
      volumes:
        - name: config
          configMap:
            name: bigdata-telemetry-fluentbit-cm
        - name: custom-filters
          configMap:
            name: {{ include "bigdata-proxy.fullname" . }}-custom-fluentbit-cm
        - name: varlog
          hostPath:
            path: /var/log/
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: telemetry-aws-credentials
          secret:
            secretName: spot-bigdata-telemetry-creds
    {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
