apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bigdata-proxy.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - events
  - services
  verbs:
  - get
  - list
  - watch
