apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bigdata-proxy.fullname" . }}-resource-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bigdata-proxy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bigdata-proxy.fullname" . }}-resource-monitor
subjects:
  - kind: ServiceAccount
    name: {{ include "bigdata-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bigdata-proxy.fullname" . }}-spark-monitor
  labels:
    {{- include "bigdata-proxy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bigdata-proxy.fullname" . }}-spark-monitor
subjects:
  - kind: ServiceAccount
    name: {{ include "bigdata-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}