{{- if .Values.telemetry.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigdata-operator.fullname" . }}-telemetry-cm
  labels:
  {{- include "bigdata-operator.labels" . | nindent 4 }}
data:
  bigdata_operator_filters.conf: |
{{ .Values.telemetry.fluentbit.configMap.config | toString | indent 6 }}
{{- end }}

