{{- if .Values.telemetry.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: bigdata-telemetry-fluentbit-cm
  labels:
  {{- include "bigdata-operator.labels" . | nindent 4 }}
data:
  parsers.conf: |
    [PARSER]
        # http://rubular.com/r/tjUt3Awgg4
        Name cri
        Format regex
        Regex ^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z)\t(?<level>[A-Z]+)\t(?<logger>[^\s]+)\t(?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser cri
        Tag kube.*
        Mem_Buf_Limit 5MB

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    @INCLUDE custom-filters.conf

    [FILTER]
        Name modify
        Match kube.*
        Add ClusterId ${CLUSTER_ID}
        Add AccountID ${ACCOUNT_ID}

    [OUTPUT]
        Name s3
        Match kube.*
        bucket                       ${AWS_BUCKET_NAME}
        region                       ${AWS_REGION}
        use_put_object               On
        total_file_size              5M
        upload_timeout               5m
{{- end }}