{{- if .Values.telemetry.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigdata-operator.fullname" . }}-custom-fluentbit-cm
  labels:
  {{- include "bigdata-operator.labels" . | nindent 4 }}
data:
  custom-filters.conf: |
    [FILTER]
        Name    grep
        Match   kube.*
        Regex   $kubernetes['labels']['bigdata.spot.io/component'] {{ include "bigdata-operator.fullname" . }}

  metrics-collection.conf: |
    [INPUT]
      name                    prometheus_scrape
      host                    0.0.0.0
      port                    8080
      tag                     {{ include "bigdata-operator.fullname" . }}
      metrics_path            /metrics
      scrape_interval         5s

    # [OUTPUT]
    #   Name                 http
    #   Match                *
    #   Host                 bigdata-telemetry-thanos-receiver-svc.spot-system.svc.cluster.local
    #   Port                 19291
    #   URI                  /api/v1/receive
    #   Format               json
    #   tls                  off
    #   tls.verify           off


    [OUTPUT]
      Name                 prometheus_remote_write
      Match                {{ include "bigdata-operator.fullname" . }}
      Host                 bigdata-telemetry-thanos-receiver-svc.spot-system.svc.cluster.local
      Port                 19291
      uri                  /api/v1/receive
      tls                  off
      tls.verify           off
      add_label            ClusterId ${CLUSTER_ID}
      add_label            AccountID ${ACCOUNT_ID}
{{- end }}
