apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bigdata-operator.fullname" . }}
  labels:
  {{- include "bigdata-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "bigdata-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- include "bigdata-operator.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bigdata-operator.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          args:
            - --leader-elect
          ports:
            - name: webhook
              containerPort: 9443
              protocol: TCP
            - name: metrics
              containerPort: 8080
              protocol: TCP
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPOTINST_BASE_URL
              value: {{ .Values.spotBaseUrl | quote }}
            - name: CHART_VERSION
              value: {{ .Chart.Version | quote }}
            - name: OCEAN_CONTROLLER_NAMESPACE
              value: {{ .Values.oceanControllerNamespace }}
            - name: BIGDATA_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  name: spot-ofas-cluster-info
                  key: proxyUrl
                  optional: true
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  name: spot-ofas-cluster-info
                  key: proxyUrl
                  optional: true
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.telemetry.enabled }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
        - name: fluentbit
          image: "{{ .Values.telemetry.fluentbit.image.repository }}:{{ .Values.telemetry.fluentbit.image.tag }}"
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          env:
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: spot-bigdata-telemetry-creds
                  key: AWS_BUCKET_NAME
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: spot-bigdata-telemetry-creds
                  key: AWS_REGION
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: spot-ofas-cluster-info
                  key: clusterId
            - name: ACCOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: spot-ofas-cluster-info
                  key: accountId
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  name: spot-ofas-cluster-info
                  key: proxyUrl
                  optional: true
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  name: spot-ofas-cluster-info
                  key: proxyUrl
                  optional: true
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: custom-config
              mountPath: /fluent-bit/etc/custom-filters.conf
              subPath: custom-filters.conf
            - name: custom-config
              mountPath: /fluent-bit/etc/metrics-collection.conf
              subPath: metrics-collection.conf
            - name: varlog
              readOnly: true
              mountPath: /var/log/
            - name: varlibdockercontainers
              readOnly: true
              mountPath: /var/lib/docker/containers
            - name: telemetry-aws-credentials
              mountPath: /root/.aws
      volumes:
        - name: config
          configMap:
            name: bigdata-telemetry-fluentbit-cm
        - name: custom-config
          configMap:
            name: {{ include "bigdata-operator.fullname" . }}-custom-fluentbit-cm
        - name: varlog
          hostPath:
            path: /var/log/
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: telemetry-aws-credentials
          secret:
            secretName: spot-bigdata-telemetry-creds
    {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}
  {{- end }}