{{- $root := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-cm
  labels:
  {{- include "bigdata-operator.labels" . | nindent 4 }}
data:
  parsers.conf: |
{{ tpl $root.Values.telemetry.fluentbit.configMap.parsers $root | indent 6 }}

  fluent-bit.conf: |
{{ tpl $root.Values.telemetry.fluentbit.configMap.config $root | indent 6 }}

