apiVersion: v1
kind: ConfigMap
metadata:
  name: bigdata-telemetry-fluentbit-cm
  labels:
  {{- include "bigdata-operator.labels" . | nindent 4 }}
data:
  parsers.conf: |
{{ .Values.telemetry.fluentbit.configMap.parsers | toString | indent 6 }}

  fluent-bit.conf: |
{{ .Values.telemetry.fluentbit.configMap.config | toString | indent 6 }}

