# Default values for bigdata-notebook-service-storage-server
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: public.ecr.aws/ocean-spark/volume-nfs
  pullPolicy: IfNotPresent
  tag: 1.0.0-ofas

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podLabels:
  spotinst.io/restrict-scale-down: "true"
  bigdata.spot.io/component: "bigdata-notebook-service-storage-server"

serviceAccount:
  create: false
  name: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 300m
    memory: 500Mi

nodeSelector: {}

tolerations:
- key: "bigdata.spot.io/unschedulable"
  operator: "Equal"
  value: "ocean-spark-system"
  effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: spotinst.io/node-lifecycle
          operator: In
          values:
          - od
        - key: spotinst.io/ocean-vng-id
          operator: Exists
        - key: bigdata.spot.io/vng
          operator: NotIn
          values:
          - ocean-spark
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: bigdata.spot.io/component
            operator: Exists
        topologyKey: "kubernetes.io/hostname"
