# Default values for bigdata-proxy
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: k8s.gcr.io/volume-nfs
  pullPolicy: IfNotPresent
  tag: 0.8

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

serviceAccount:
  create: false
  name: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 50Mi

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: spotinst.io/node-lifecycle
          operator: In
          values:
          - od
