{{- if .Values.telemetry.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigdata-notebook-workspace.fullname" . }}-telemetry-cm
  labels:
  {{- include "bigdata-notebook-workspace.labels" . | nindent 4 }}
data:
  bigdata_notebook_workspace_filters.conf: |
{{ .Values.telemetry.fluentbit.configMap.config | toString | indent 6 }}
{{- end }}

