apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bigdata-notebook-workspace.labels" . | nindent 4 }}
    {{- with .Values.sharedLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "bigdata-notebook-workspace.annotations" . | nindent 4 }}
    {{- with .Values.sharedAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bigdata-notebook-workspace.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "bigdata-notebook-workspace.annotations" . | nindent 8 }}
        {{- with .Values.sharedAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "bigdata-notebook-workspace.labels" . | nindent 8 }}
        {{- with .Values.sharedLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bigdata-notebook-workspace.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: workspace
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort.port }}
              name: {{ .Values.containerPort.name }}
            - containerPort: 8877
              name: http-response
          env:
          {{- if .Values.pvc.create }}
          - name: "CHOWN_HOME"
            value: "yes"
          - name: "CHOWN_HOME_OPTS"
            value: "-R"
          {{- end }}
          {{- if .Values.gatewayClient.enabled }}
          - name: "SPOTINST_AUTH_TOKEN"
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: {{ .Values.gatewayClient.secretKeyToken }}
          {{- end }}
          {{- if .Values.pvc.create }}
          - name: GP_OFAS_WKSP_ID
            value: {{ .Release.Name }}
          - name: GP_OFAS_CLUSTER_ID
            value: "osc-cec441dc"
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mountPath }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.telemetry.enabled }}
        - name: fluentbit
          image: "{{ .Values.telemetry.fluentbit.image.repository }}:{{ .Values.telemetry.fluentbit.image.tag }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          env:
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: spot-bigdata-telemetry-creds
                  key: AWS_BUCKET_NAME
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: spot-bigdata-telemetry-creds
                  key: AWS_REGION
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: spot-ofas-cluster-info
                  key: clusterId
            - name: ACCOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: spot-ofas-cluster-info
                  key: accountId
          volumeMounts:
            - name: telementry-global-config
              mountPath: /opt/bitnami/fluent-bit/conf/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: telementry-custom-config
              mountPath: /opt/bitnami/fluent-bit/conf/custom-filters.conf
              subPath: custom-filters.conf
            - name: telementry-global-config
              mountPath: /opt/bitnami/fluent-bit/conf/parsers.conf
              subPath: parsers.conf
            - name: telementry-custom-config
              mountPath: /opt/bitnami/fluent-bit/conf/metrics-collection.conf
              subPath: metrics-collection.conf
            - name: varlog
              readOnly: true
              mountPath: /var/log/
            - name: varlibdockercontainers
              readOnly: true
              mountPath: /var/lib/docker/containers
            - name: telemetry-aws-credentials
              mountPath: /.aws
      {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- if or .Values.pvc.create .Values.telemetry.enabled }}
      volumes:
        {{- if .Values.pvc.create }}
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
        {{- end }}
        {{- if .Values.telemetry.enabled }}
        - name: telementry-global-config
          configMap:
            name: bigdata-common-telemetry-fluentbit-cm
        - name: telementry-custom-config
          configMap:
            name: {{ include "bigdata-notebook-workspace.fullname" . }}-telemetry-cm
        - name: varlog
          hostPath:
            path: /var/log/
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: telemetry-aws-credentials
          secret:
            secretName: spot-bigdata-telemetry-creds
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
