apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bigdata-notebook-workspace.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - 'configmaps'
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bigdata-notebook-workspace.fullname" . }}-pod-watcher
rules:
  - apiGroups:
      - ""
    resources:
      - 'pods'
      - 'services'
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bigdata-notebook-workspace.fullname" . }}-killer
rules:
  - apiGroups:
    - sparkoperator.k8s.io
    resources:
    - '*'
    verbs:
    - 'list'
    - 'patch'
