# Default values for bigdata-proxy
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 066597193667.dkr.ecr.us-east-1.amazonaws.com/private/bigdata-proxy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.1.0-3002031f

imagePullSecrets:
  - name: spot-bigdata-image-pull

port: 8080
logLimit: 0
eventTimeout: 10m
sparkAppsNamespace: spark-apps


nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: bigdata-proxy

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 50Mi

nodeSelector: {}

tolerations: []

affinity: {}
