# Default values for bigdata-noteboook-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 066597193667.dkr.ecr.us-east-1.amazonaws.com/private/bigdata-notebook-service
  pullPolicy: IfNotPresent
  tag: master

imagePullSecrets:
  - name: spot-bigdata-image-pull

port: 8080

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: bigdata-notebook-service

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 2
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 500Mi

nodeSelector: {}

tolerations: []

affinity: {}
