# Default values for bigdata-noteboook-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 598800841386.dkr.ecr.us-east-2.amazonaws.com/private/bigdata-notebook-service  # 066597193667.dkr.ecr.us-east-1.amazonaws.com/private/bigdata-notebook-service
  pullPolicy: Always  # IfNotPresent
  tag: notebook-service-integration  # master

imagePullSecrets:
  - name: spot-bigdata-image-pull-dev  # spot-bigdata-image-pull

port: 8888

kernel:
  namespace: "spark-apps"
  portMin: 50000  # Port range usable by kernels. Each kernel takes one port.
  portMax: 50020
  launchTimeout: 600  # Timeout for kernel launching in seconds. Nginx timeout is also set to this value.
  cullIdleTimeout: 3600  # Timeout for an idle kernel before it's culled in seconds. Default is 1 hour.

egBaseUrl: "notebooks"
egLogLevel: "DEBUG"

spotBaseUrl: "https://api.spotinst.io"
spotCredsNamespace: "kube-system"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: bigdata-notebook-service

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext: {}

resources:
  limits:
    cpu: 2
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 500Mi

nodeSelector: {}

tolerations: []

affinity: {}
