apiVersion: v2
name: bigdata-telemetry
description: A Helm chart for the Spot Big Data Telemetry components
type: application
version: 0.1.1
appVersion: "1.16.0"
home: https://github.com/spotinst/charts
icon: https://docs.spot.io/_media/images/spot_mark.png
sources:
- https://github.com/spotinst/bigdata-telemetry
keywords:
- spot
- spark
maintainers:
- name: z4ck404
  email: zakaria.elbazi@netapp.com
