# Default values for bigdata-telemetry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

podAnnotations: {}

podLabels:
  bigdata.spot.io/component: "bigdata-telemetry"


fluentbit:
  parsers: |
    [PARSER]
        # http://rubular.com/r/tjUt3Awgg4
        Name cri
        Format regex
        Regex ^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z)\t(?<level>[A-Z]+)\t(?<logger>[^\s]+)\t(?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
  confing: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser cri
        Tag kube.*
        Mem_Buf_Limit 5MB

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name modify
        Match kube.*
        Add ClusterId ${CLUSTER_ID}
        Add AccountID ${ACCOUNT_ID}
        Add OrganizationId ${ORGANIZATION_ID}

    # [FILTER]
    #     Name    grep
    #     Match   kube.*
    #     Regex   $kubernetes['labels']['bigdata.spot.io/component'] .

    [OUTPUT]
        Name s3
        Match kube.*
        bucket                       ${AWS_BUCKET_NAME}
        region                       ${AWS_REGION}
        use_put_object               On
        total_file_size              10M
        upload_timeout               15m

thanos:
  image:
    repository: quay.io/thanos/thanos
    tag: v0.15.0

  additionalPodLabels:
    bigdata.spot.io/telemetry: "thanos"


nodeSelector: {}

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: spotinst.io/ocean-vng-id
          operator: Exists
        - key: bigdata.spot.io/vng
          operator: NotIn
          values:
          - ocean-spark
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: bigdata.spot.io/component
            operator: Exists
        topologyKey: "kubernetes.io/hostname"

tolerations:
- key: "bigdata.spot.io/unschedulable"
  operator: "Equal"
  value: "ocean-spark-system"
  effect: "NoSchedule"
- key: "kubernetes.azure.com/scalesetpriority"
  operator: "Equal"
  value: "spot"
  effect: "NoSchedule"
