{{- if .Values.telemetry.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigdata-spark-watcher.fullname" . }}-custom-fluentbit-cm
  labels:
  {{- include "bigdata-spark-watcher.labels" . | nindent 4 }}
data:
  custom-filters.conf: |
    [FILTER]
        Name    grep
        Match   kube.*
        Regex   $kubernetes['labels']['bigdata.spot.io/component'] {{ include "bigdata-spark-watcher.fullname" . }}
{{- end }}
