apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bigdata-spark-watcher.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "namespaces"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    resourceNames:
      - "spotinst-kubernetes-cluster-controller-config"
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - "secrets"
    resourceNames:
      - "spotinst-kubernetes-cluster-controller"
    verbs:
      - get
  - apiGroups:
      - sparkoperator.k8s.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bigdata-spark-watcher.fullname" . }}-killer
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create