---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bigdata-spark-watcher.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bigdata-spark-watcher.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "bigdata-spark-watcher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bigdata-spark-watcher.fullname" . }}
  namespace: {{ .Values.sparkAppsNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bigdata-spark-watcher.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bigdata-spark-watcher.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}