apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bigdata-spark-watcher.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "namespaces"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    resourceNames:
      - "spotinst-kubernetes-cluster-controller-config"
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - "secrets"
    resourceNames:
      - "spotinst-kubernetes-cluster-controller"
      - "spot-bigdata-log-collector-creds"
    verbs:
      - get
  - apiGroups:
      - sparkoperator.k8s.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # required for leader-election (high-availability)
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bigdata-spark-watcher.fullname" . }}-killer
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
