---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigdata-spark-watcher.fullname" . }}-metrics
  labels:
    {{- include "bigdata-spark-watcher.labels" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "bigdata-spark-watcher.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
