apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigdata-spark-watcher.fullname" . }}-telemetry-cm
  labels:
  {{- include "bigdata-spark-watcher.labels" . | nindent 4 }}
data:
  custom-filters.conf: |
    [FILTER]
        Name    grep
        Match   kube.*
        Regex   $kubernetes['labels']['bigdata.spot.io/component'] {{ index .Values.podLabels "bigdata.spot.io/component" }}

  metrics-collection.conf: |
    [INPUT]
      name                    prometheus_scrape
      host                    0.0.0.0
      port                    8080
      tag                     {{ include "bigdata-spark-watcher.fullname" . }}
      metrics_path            /metrics
      scrape_interval         5s

    [OUTPUT]
      Name                 prometheus_remote_write
      Match                {{ include "bigdata-spark-watcher.fullname" . }}
      Host                 bigdata-telemetry-thanos-receiver-svc.spot-system.svc.cluster.local
      Port                 19291
      uri                  /api/v1/receive
      tls                  off
      tls.verify           off
      Workers              1
